# Generated by Django 3.1 on 2020-09-15 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('workout_date', models.DateField()),
                ('category', models.CharField(choices=[('', 'Select Workout Category'), ('crossfit', 'Crossfit'), ('gymnastics', 'Gymnastics'), ('metcon', 'Metcon'), ('olympic weightlifting', 'Olympic Weightlifting'), ('strength and conditioning', 'Strength & Conditioning')], max_length=25)),
                ('part_a', models.TextField()),
                ('part_b', models.TextField()),
                ('part_c', models.TextField()),
                ('coach_comments', models.TextField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
