# Generated by Django 3.1 on 2020-09-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='category',
            field=models.CharField(choices=[('', 'Select Workout Category'), ('crossfit', 'Crossfit'), ('gymnastics', 'Gymnastics'), ('metcon', 'Metcon'), ('olympic weightlifting', 'Olympic Weightlifting'), ('strength and conditioning', 'Strength & Conditioning')], default='', max_length=25),
            preserve_default=False,
        ),
    ]
