# Generated by Django 3.1 on 2020-09-19 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workouts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='coach',
            field=models.ForeignKey(default=workouts.models.get_coach, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
